### ISSUE TITLE
Doesn't work on iOS 9

### ISSUE THREAD

**Issue by sgtpepper43** [hampusohlsson/browser-deeplink#16]
Trying to open the link always fails on iOS 9, whether you have the app or not.

**Comment by ohh2ahh** [comment]
+1

**Comment by stefangomez** [comment]
iOS 9 added privacy features where apps can't navigate or "detect" apps installed --assuming this affected safari as well :/ 

having a link like `<a href="deeplink://destination">link</a>` works though.

**Comment by sgtpepper43** [comment]
Even just assigning `window.location` works. It seems that after all the effort of introducing their new "Universal Links" thing that automatically checks if an app exists for links between different apps, they decided doing the same thing for Safari was not something they wanted to pursue... I guess.

**Comment by shailu** [comment]
The below approach fixes this issue:
https://github.com/mderazon/node-deeplink/issues/8
but creates new one:
https://github.com/mderazon/node-deeplink/issues/9

**Comment by omihailo** [comment]
Can we expect fixing of this issue soon?
The users are migrating to iOS 9 very fast, so we are already experiencing some issues with it.
There are apps which really depends on the deeplink script.

**Comment by j4zz** [comment]
@omihailo As @sgtpepper43 already mentioned, Apple likely expects you to implement [universal links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html#//apple_ref/doc/uid/TP40016308-CH12) (see the [WWDC talk](https://developer.apple.com/videos/wwdc/2015/?id=509)).

As long as your app is not an app launcher or something, implementing universal links is likely the way to go, since Apple seems to conceptually treat hitting Safari as the “no deeplink recognized” fallback. Differently stated: Safari conceptually doesn’t expect automatically triggered depplinks, since universal links are recognized before the page is fully loaded in Safari.

**Comment by kennyth01** [comment]
as @shailu highlighted, here's the quick fix for this issue:
go to line 188 replace and use the snippet below:
```javascript
var ua = window.navigator.userAgent;
        if (ua.match(/CriOS/) || (ua.match(/Safari/) && ua.match(/Version\/9/))) {
            //do another approach...
            document.location = uri;
        } else {
            var iframe = document.createElement("iframe");
            iframe.onload = function() {
                clearTimeout(timeout);
                iframe.parentNode.removeChild(iframe);
                window.location.href = uri;
            };
            iframe.src = uri;
            iframe.setAttribute("style", "display:none;");
            document.body.appendChild(iframe);
        }
```

**Comment by andyvb** [comment]
@kennyth01, unfortunately as @shailu mentioned, the workaround causes an error dialog to appear if the user doesn't have your app installed. Unfortunately that's a non-starter for us. The only real solution for us is to use Universal Links.

**Comment by kennyth01** [comment]
@andyvb what do you mean by "error" dialog? I didn't saw any error dialog?

**Comment by andyvb** [comment]
@kennyth01 It's in the ticket shailu linked to (https://github.com/mderazon/node-deeplink/issues/9). You see this dialog if you don't have the app installed:
![safari_canot_open_page](https://cloud.githubusercontent.com/assets/1017642/10242163/c237ee42-68a3-11e5-81eb-f1da5f3c43ad.png)

**Comment by kopiro** [comment]
The best solution I found is to:

```
location.href = DEEP_LINK
location.href = FALLBACK_LINK
```

With this solution, if the app is not installed, an error dialog is thrown, but after clicking OK another dialog appear with the question "Open App store?".

---

I print also a small HTML with a link to the fallback, in the case the user clicks "Cancel" of the dialogs.

**Comment by mderazon** [comment]
ios 9.2 have made things worse. see [this blog post](http://email.branch.io/ios-9.2-release-important-announcement)

**Comment by shailu** [comment]
From the link:
>"What changed in iOS 9.2?
>
>Apple changed the 'Open App' modal from a blocking modal to a non blocking modal. When you try to >open up the app, the modal will no longer block Javascript from executing, meaning that the fallback >redirect to the App Store will execute immediately before the user can click 'Open App'."

Wasn't this the case even in ios 9.0?

**Comment by leonyu** [comment]
In iOS 9.0, setting a new URL after the "non-blocking modal" cause the dialog box to be dismissed as if user clicked "Open", which is useful behavior. 

In 9.2, setting a new URL causes dialog box to be dismissed as if user clicked "Cancel", which is does not help the cause.

**Comment by robindra** [comment]
@kopiro: Is there any way to detect user click on cancel button in the popup so that we can directly redirect to the fallback url without printing the small html page.

**Comment by kopiro** [comment]
I think you cant, it's an OS dialog you can't just control.

**Comment by leonyu** [comment]
For user action, you can guess using `requestAnimationFrame`. Due to the fact that both dialog box and app switching takes up more GPU than scrolling a page, the timing difference between successive `requestAnimationFrame` could be used to differentiate various user actions. It is fairly complicated and requires benchmarking to get any meaningful result, so it is not worthwhile for most uses, since you can't use it to tell if app is installed or not. 

Also there is slight difference in `window.open('customURL://blah')` on 9.2 between having the app and not having the app. If the app exists, the popup would close automatically when user cancel, if the app doesn't exist, the popup would stay. This may be used to detect if user has the app installed if we preemptively open and close a pop-up. However, given the horrid user experience that would entail, I didn't bother investigating further. No clue if it is still the case in 9.3 or 10.

**Comment by albandaft** [comment]
@leonyu this could be a nice hack (but apple is annoying with this changes....)

**Comment by sgtpepper43** [comment]
I'm closing this because it's been three years and I don't want to see this in my issues list anymore :grin: Plus as of b0bd1cf5bcb7e220fc02c3174b54589e49ef5e67 this project is no longer maintained.
